safe: true
future: true
exclude: [.gitattributes, .gitignore, flywaydb.org.iml, flywaydb.org.ipr, flywaydb.org.iws, README.md, CNAME, Gemfile, Gemfile.lock, .idea/workspace.xml]
flywayVersion: 9.8.0
betaFlywayVersion: 9.0.0-beta5
enterpriseUrl: https://download.red-gate.com/maven/release/org/flywaydb/enterprise
markdown: kramdown
url: https://flywaydb.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
